### ISSUE TITLE
Can not download all versions of the dataset

### ISSUE THREAD

**Issue by Alberta-Lee** [knowledgedefinednetworking/NetworkModelingDatasets#10]
For [Datasets v0](https://github.com/BNN-UPC/NetworkModelingDatasets/tree/master/datasets_v0) and [Dataset v1](https://github.com/BNN-UPC/NetworkModelingDatasets/tree/master/datasets_v1), i don't have permission to access this resource.
And for other remaining versions of the dataset, i can't reach their pages.

**Comment by albert-lopez** [comment]
The datasets are available again. Thanks to notifying us.
