### ISSUE TITLE
how to understand the dataset

### ISSUE THREAD

**Issue by ablazet** [knowledgedefinednetworking/NetworkModelingDatasets#2]
Dear sir,
I have two questions about this dataset. First,what is the field in the matrix of route and delay?  Second,how to gain the meanings of the matrices ? would you please tell me more information of the dataset?

**Comment by jsuarezv** [comment]
Hello,
Please find this information in the README files and also in the API repository associated to the datasets. Let me know if you have any additional question.

Regards,
José
