### ISSUE TITLE
*.ned file

### ISSUE THREAD

**Issue by cyber520** [knowledgedefinednetworking/NetworkModelingDatasets#3]
*.ned file: Describes the network topology including the link capacities.

Hello, the *.ned file can't find int the dataset, could you please give me one ? Thanks.

**Comment by jsuarezv** [comment]
Hello,
Could you point me to the specific dataset you are referring to (version and topology)? Also, we strongly recommend use the API associated to the datasets. You can find more information in the README files. It may help you process easily the data and structure it in a user-friendly manner.

**Comment by cyber520** [comment]
that's solved, thks. could you please give me the code of your another paper, ie. DRL+GNN, I'm interested in it now,  thanks!

**Comment by cyber520** [comment]
coule you please tell me how to generate the simulation file of dataset v1 in the omit++, I want to get some files in my own way.

**Comment by jsuarezv** [comment]
Hello,
To generate our datasets we use an in-house implementation with OMNET++ that is not publicly available at this moment. In case we decide to make it public we will announce it.

**Comment by cyber520** [comment]
Hello,
For the datasetV1, how do you get the label "**delay**" in your simulation in OMNET++,  and what's the mean of  "**bandwidth**" of all src-dst paths? I feel confused about the  **two** settings, could you please teach me in details, thank you.

**Comment by jsuarezv** [comment]
Hello,
"delay" is measured as the mean per-packet delay on each source-destination path, while "bandwidth" is the traffic volume (in kbps) sent in each source-destination pair. I hope this answers your question.

**Comment by cyber520** [comment]
I got it, thank you. And I still want the configuration in your omnet++, could you please send me one copy file?

**Comment by jsuarezv** [comment]
The config files we use in our internal implementation are the ones publicly available in our datasets (i.e., topology, routing, etc). Also, we use \<lower lambda max>-\<upper lambda max> to adapt the input traffic. Thus, per-source-destination traffic follows a uniform distribution in the range [0.1, lambda]. In turn, in each simulation "lambda" is selected from a uniform distribution in the range [lower lambda max,upper lambda max]

**Comment by cyber520** [comment]
well, I mean the entire files of omnet++, I have generated some new datasets of different topologys  to test the generality with the same experiment setting as yours. As tested in my experiment setting, the performance of Routent is pool in my datasets.
