### ISSUE TITLE
Datasets not available

### ISSUE THREAD

**Issue by diegocervera** [knowledgedefinednetworking/NetworkModelingDatasets#4]
Hi,

I am trying to reproduce the results of the RouteNet paper, but it seems the datasets are no longer available (in datasets_v1). When clicking on any of the links I get the following message: "Forbidden. You don't have permission to access this resource."

Are the datasets publicly available somewhere else?

Many thanks,
Diego

**Comment by jsuarezv** [comment]
Dear Diego,
Sorry, the datasets should be already available.

Thanks,
José
