### ISSUE TITLE
Release the simulator used to generate the dataset

### ISSUE THREAD

**Issue by pedosb** [knowledgedefinednetworking/NetworkModelingDatasets#5]
Hello!

Let me first congratulate you on the great research and on the initiative of releasing the contents to allow further improvements. That's much appreciated.

Now, to my question, do you have any plans to release the custom code of the simulator that you used to generate the dataset? It could be used to create further customizations to more specific use-cases.

BR,
Pedro

**Comment by jsuarezv** [comment]
Hello Pedro,
Thank you for your interest.
Sorry, the code of our simulator is not open source yet. We will make an announcement once we release it via the following mailing list:
kdn-users@knowledgedefinednetworking.org
To post emails it is first needed to subscribe through this link: 
https://mail.knowledgedefinednetworking.org/cgi-bin/mailman/listinfo/kdn-users

Regards,
José

**Comment by Happpyll** [comment]
Hello,
Sorry to bother. 
I can't download the dataset V0. It says "You don't have permission to access this resource."
Could you please check it?

ll

**Comment by albert-lopez** [comment]
Hello Happpyll,

Thanks to notifying us this error. We have checked it and now the datasets are accessible again.

Regards

Albert
