### ISSUE TITLE
Bandwidths in both directions are not equal in dataset_ v0

### ISSUE THREAD

**Issue by ideafang** [knowledgedefinednetworking/NetworkModelingDatasets#6]
In dataset_v0 nsfnet dataset, I unziped one of the results*.tar.gz and try to figure out the data means.
The `README.md` shows in `simulationResults.txt` file, Bandwidths are in both directions. So i try to check the bandwidth between node0 and node2.
```python
import numpy as np
s = np.loadtxt('.\simulationResults.txt', dtype=float, delimiter=',', usecols=np.arange(1960))
line = s[0]
src = 0
dst = 2
n = 14
bw1 = line[(src*n+dst)*3]
bw2 = line[(dst*n+src)*3]
print(bw1, bw2)
```
but the result `0.427143 0.648329` was not same.

**Comment by jsuarezv** [comment]
Hello,
Thank you for your interest in our datasets.
Perhaps the description in the README file was a bit confusing. We have rewritten it accordingly.
These values show the average traffic rate sent only in one direction (i.e., from node0 to node1). In our simulations this is independent to the traffic sent in the opposite direction (e.g., from node0 to node1), so typically you will find different values in each direction.

By the way, each dataset has an associated API to facilitate reading and processing the data. For this dataset, you can use the API at this [link](https://github.com/BNN-UPC/datanetAPI/tree/dataset_v0).

BR,
José

**Comment by ideafang** [comment]
Thank you for your prompt reply! It's a great work and I will study this meaningful work carefully in the next few weeks.
