### ISSUE TITLE
datasets not accessible

### ISSUE THREAD

**Issue by zeeros** [knowledgedefinednetworking/NetworkModelingDatasets#7]
I've been trying to download the datasets referenced in your [public repository](https://github.com/BNN-UPC/NetworkModelingDatasets), but only v2 and v3 (of the GNNet Challenges 2020 and 2021)  are available while all the others are not accessible (v0 and v1 [here](https://knowledgedefinednetworking.org/data), v4 [here](https://github.com/BNN-UPC/NetworkModelingDatasets/tree/master/datasets_v4)).

I would be interested to access these datasets, is there any way to do it?

**Comment by albert-lopez** [comment]
Datasets are accessible again. Thanks to let us know.
