### ISSUE TITLE
Dataset is not available

### ISSUE THREAD

**Issue by Feblu** [knowledgedefinednetworking/NetworkModelingDatasets#9]
When I download nsfnet-v0, the dataset is not available because the link is  no longer active.
https://github.com/BNN-UPC/NetworkModelingDatasets/blob/83109a993390851404e52b0141f38535a95dfa19/datasets_v0/README.md?plain=1#L77

**Comment by Alberta-Lee** [comment]
Me too, I had the same problem

**Comment by albert-lopez** [comment]
The datasets are available again. Thanks to notifying us.
